# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: digitalnaorreto3
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: digitalnao-app
# "service" is the name of this project. This will also be added to your AWS resource names.
service: digitalnao-reto3

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - dynamodb:* # Gives permission to all dynamodb actions
      Resource: 
        - arn:aws:dynamodb:us-east-1:381492209894:table/TaskTable

functions:
  api:
    handler: src/handler.handler
    events:
      - httpApi:
          path: /
          method: get

  createTask:
    handler: src/addTask.addTask
    events:
      - httpApi:
          path: /tasks
          method: post

    createTask2:
    handler: src/addTask.addTask2
    events:
      - httpApi:
          path: /tasks2
          method: post

resources:
  Resources:
    TaskTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: TaskTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH